meta_product_name: "Derby Match"
meta_title: "Derby Match - Find a team, plan a game"
meta_description: "Derby Match takes away the pain of each Roller Derby interleague responsable when searching for a team to play against outside of official championship."
meta_image: "cover.png" # should exist in `app/assets/images/`
